# Generated by Django 4.0.6 on 2022-08-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_photo_name_alter_photo_zip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
